### PR TITLE
feat: Add Splash Screen

### PR DESCRIPTION
**Pull request by PPartisan**
Adds a simple splash screen using app branding [issue #9]
screenshot_1484221818

### CODE REVIEW

**Comment by Dvik** [comment]
Instead of using PNG, consider using SVG images. 
Also, the files changed are more than the files actually changed by you. Please consider pulling the repo before pushing.

**Comment by PPartisan** [comment]
I went with a PNG because I'm not sure it's possible to use vector images in a `layer-list` drawable on API levels below 23 [with correct scaling](http://stackoverflow.com/questions/34831142/how-to-center-vector-drawable-in-layer-list-without-scaling). Here's an example using the same vector image on [API 22](https://s23.postimg.org/9gmzzhfor/Screenshot_1484234501.png) and [API 23](https://s23.postimg.org/4w0tkjvzf/Screenshot_1484234489.png) for comparison.

Apologies for the excess files included in the pull request. I did sync with the upstream repository first so I'm not sure why that's happened. I can look into removing them my end.

**Comment by chashmeetsingh** [comment]
Also @PPartisan next time you want to work on any issue, comment on that issue that you want to work on it so that others don't land up starting with the same issue 😄

**Comment by PPartisan** [comment]
Will do, thanks @chashmeetsingh :smile:

**Pull request merged**
